development:
  rabbit_mq:
    host: localhost
    port: 5672
    user: stub
    pass: stub
    vhost: stub

test:
  rabbit_mq:
    host:
    port:
    user:
    pass:
    vhost:

production:
  rabbit_mq:
    host:
    port:
    user:
    pass:
    vhost:
